#!/usr/bin/env node
import type { GeneratorOptions } from "@prisma/generator";
import { DMMF, generatorHandler } from "@prisma/generator-helper";
import fs from "fs/promises";
import path from "path";
import { determineEffectMajor, type EffectMajor } from "./effect-major";
import { generateSchemas, rebaseImportPath } from "./schemas";

// The suppression directives exempt the generated implementation from type
// checking and linting, mirroring Prisma's own generated client header.
// `// @ts-nocheck` insures against consumer tsconfig variations
// (exactOptionalPropertyTypes etc.) the generated code isn't tested under;
// exported signatures still type-check consumer call sites.
function headerFor(noCheck: boolean) {
  return (
    `// This file was generated by prisma-effect-generator, do not edit manually.\n` +
    (noCheck
      ? `/* eslint-disable */\n// biome-ignore-all lint: generated file\n// @ts-nocheck\n`
      : "")
  );
}

// Utility function to convert PascalCase to camelCase
function toCamelCase(str: string) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

// Prisma passes generator config values as strings (or string arrays for
// repeated keys); accept only "true"/"false".
function parseBooleanConfig(
  value: string | string[] | undefined,
  name: string,
  defaultValue: boolean,
): boolean {
  const raw = Array.isArray(value) ? value[0] : value;
  if (raw === undefined) {
    return defaultValue;
  }
  if (raw === "true") {
    return true;
  }
  if (raw === "false") {
    return false;
  }
  throw new Error(
    `effect-prisma-generator: ${name} must be "true" or "false". Got "${raw}".`,
  );
}

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./generated/effect.ts",
      prettyName: "Prisma Effect Generator",
    };
  },

  async onGenerate(options: GeneratorOptions) {
    const models = options.dmmf.datamodel.models;
    const outputPath = options.generator.output?.value;
    const clientImportPath = options.generator.config.clientImportPath;

    if (!outputPath) {
      throw new Error("effect-prisma-generator: No outputPath specified");
    }
    if (Array.isArray(clientImportPath)) {
      throw new Error(
        "effect-prisma-generator: clientImportPath must be a string. Array given.",
      );
    }
    if (typeof clientImportPath !== "string") {
      throw new Error("effect-prisma-generator: No clientImportPath specified");
    }
    if (!outputPath.toLowerCase().endsWith(".ts")) {
      throw new Error("effect-prisma-generator: outputPath must be a ts file");
    }

    const hasTypedSql = [options.generator, ...options.otherGenerators].some(
      (g) => g.previewFeatures.includes("typedSql"),
    );

    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    const effectMajor = determineEffectMajor(
      options.generator.config.effectVersion,
      [outputDir, process.cwd()],
    );

    // Intentionally undocumented escape hatch: this repo's test suite sets
    // noCheck = "false" to type-check generated output as-is.
    const noCheck = parseBooleanConfig(
      options.generator.config.noCheck,
      "noCheck",
      true,
    );

    await generateUnifiedService(
      [...models],
      options.dmmf.mappings.modelOperations,
      outputPath,
      clientImportPath,
      hasTypedSql,
      effectMajor,
      noCheck,
    );

    const schemaOutput = options.generator.config.schemaOutput;
    if (schemaOutput !== undefined) {
      if (Array.isArray(schemaOutput)) {
        throw new Error(
          "effect-prisma-generator: schemaOutput must be a string. Array given.",
        );
      }
      if (!schemaOutput.toLowerCase().endsWith(".ts")) {
        throw new Error(
          "effect-prisma-generator: schemaOutput must be a ts file",
        );
      }
      // Custom config values arrive unresolved; resolve like Prisma resolves
      // `output` — against the schema file holding the generator block.
      const schemaOutputPath = path.resolve(
        path.dirname(options.generator.sourceFilePath),
        schemaOutput,
      );
      await generateSchemas(
        [...models],
        [...options.dmmf.datamodel.enums],
        schemaOutputPath,
        rebaseImportPath(
          clientImportPath,
          outputDir,
          path.dirname(schemaOutputPath),
        ),
        effectMajor,
        headerFor(noCheck),
      );
    }
  },
});

function generateRawSqlOperations(hasTypedSql: boolean) {
  const typedSqlOperation = hasTypedSql
    ? `

    $queryRawTyped: <T>(typedQuery: runtime.TypedSql<unknown[], T>) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$queryRawTyped(typedQuery),
          catch: (error) => mapError(error, "$queryRawTyped", "Prisma")
        }),
      ),`
    : "";

  return `
    $executeRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => (Array.isArray(args) ? client.$executeRaw(args[0], ...args.slice(1)) : client.$executeRaw(args)),
          catch: (error) => mapError(error, "$executeRaw", "Prisma")
        }),
      ),

    $executeRawUnsafe: (query: string, ...values: any[]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$executeRawUnsafe(query, ...values),
          catch: (error) => mapError(error, "$executeRawUnsafe", "Prisma")
        }),
      ),

    $queryRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => (Array.isArray(args) ? client.$queryRaw(args[0], ...args.slice(1)) : client.$queryRaw(args)),
          catch: (error) => mapError(error, "$queryRaw", "Prisma")
        }),
      ),

    $queryRawUnsafe: (query: string, ...values: any[]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$queryRawUnsafe(query, ...values),
          catch: (error) => mapError(error, "$queryRawUnsafe", "Prisma")
        }),
      ),${typedSqlOperation}`;
}

function generateModelOperations(
  models: DMMF.Model[],
  modelOperations: DMMF.Mappings["modelOperations"],
) {
  const mappingByModel = new Map(
    modelOperations.map((m) => [m.model, m as Record<string, unknown>]),
  );
  return models
    .map((model) => {
      const modelName = model.name;
      const modelNameCamel = toCamelCase(modelName);
      // A model with a required `Unsupported(...)` field (e.g. a pgvector
      // `vector` column) cannot be created through the typed client, so Prisma
      // omits its create/createMany/createManyAndReturn/upsert operations and
      // their `*Args` types. Emit each operation only when its DMMF mapping
      // exists; Prisma 7 names the single-record mappings `createOne`/
      // `upsertOne`, older majors used `create`/`upsert`.
      const mapping = mappingByModel.get(modelName) ?? {};
      const hasOp = (...keys: string[]) =>
        keys.some((key) => Boolean(mapping[key]));

      // Operations are typed with Prisma.Args / Prisma.Result over the
      // concrete client — the extension-author utilities that resolve for any
      // delegate. SelectSubset keeps excess-property strictness even for
      // widened non-literal args (Prisma.Exact does not — pinned in
      // tests/typelevel.test.ts). The delegate call needs the cast because
      // with a free generic A the delegate's own generics don't bind to A —
      // the declared Result<> return is what consumers infer from;
      // tests/typelevel.test.ts pins those shapes and the integration tests
      // cover runtime behavior.
      const emitOperation = (operationName: string, errorMapper: string) => `
      ${operationName}: <A extends Prisma.Args<PrismaClient["${modelNameCamel}"], "${operationName}">>(args: Prisma.SelectSubset<A, Prisma.Args<PrismaClient["${modelNameCamel}"], "${operationName}">>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: (): Promise<Prisma.Result<PrismaClient["${modelNameCamel}"], A, "${operationName}">> => client.${modelNameCamel}.${operationName}(args),
            catch: (error) => ${errorMapper}(error, "${operationName}", "${modelName}")
          }),
        ),
`;

      // create/createMany/createManyAndReturn/upsert/updateManyAndReturn are
      // omitted by Prisma for some models or providers (a required
      // Unsupported() field, or a provider without the operation). Emit each
      // only when its DMMF mapping exists — otherwise Prisma.Args would resolve
      // to `any`, silently exposing an untyped method that fails at runtime.
      const createOperation = hasOp("createOne", "create")
        ? emitOperation("create", "mapCreateError")
        : "";
      const createManyOperation = hasOp("createMany")
        ? emitOperation("createMany", "mapCreateError")
        : "";
      const createManyAndReturnOperation = hasOp("createManyAndReturn")
        ? emitOperation("createManyAndReturn", "mapCreateError")
        : "";
      const upsertOperation = hasOp("upsertOne", "upsert")
        ? emitOperation("upsert", "mapCreateError")
        : "";
      const updateManyAndReturnOperation = hasOp("updateManyAndReturn")
        ? emitOperation("updateManyAndReturn", "mapUpdateManyError")
        : "";

      const operations = [
        emitOperation("findUnique", "mapFindError"),
        emitOperation("findUniqueOrThrow", "mapFindOrThrowError"),
        emitOperation("findFirst", "mapFindError"),
        emitOperation("findFirstOrThrow", "mapFindOrThrowError"),
        emitOperation("findMany", "mapFindError"),
        createOperation,
        createManyOperation,
        createManyAndReturnOperation,
        emitOperation("delete", "mapDeleteError"),
        emitOperation("update", "mapUpdateError"),
        emitOperation("deleteMany", "mapDeleteManyError"),
        emitOperation("updateMany", "mapUpdateManyError"),
        updateManyAndReturnOperation,
        upsertOperation,
        "\n      // Aggregation operations\n",
        emitOperation("count", "mapFindError"),
        emitOperation("aggregate", "mapFindError"),
      ].join("");

      // Field references (client.<model>.fields) are inert markers used to
      // compare two columns of the same model in a filter; they touch no
      // connection, so they pass through as a plain value rather than an
      // Effect. Reading them off the base client is correct even inside a
      // transaction: a ref only names a column, and a transaction client's own
      // refs are equivalent values (separate objects, same contents).
      return `    ${modelNameCamel}: {
      fields: client.${modelNameCamel}.fields,
${operations}
      // groupBy's input validation (having/orderBy fields must appear in "by")
      // is expressed by the shared GroupBy* helpers, since Prisma.Args cannot
      // capture it. Only the result type comes from Prisma.Result.
      groupBy: <T extends Prisma.${modelName}GroupByArgs>(
        args: Prisma.SubsetIntersection<
          T,
          Prisma.${modelName}GroupByArgs,
          GroupByOrderByArgument<Prisma.${modelName}GroupByArgs, T>
        > & GroupByInputErrors<T>,
      ) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: (): Promise<Prisma.Result<PrismaClient["${modelNameCamel}"], T, "groupBy">> => client.${modelNameCamel}.groupBy(args),
            catch: (error) => mapFindError(error, "groupBy", "${modelName}")
          }),
        ),
    }`;
    })
    .join(",\n\n");
}

// The pieces of the emitted service that differ between effect v3 and v4. The
// rest of the generated file is identical across majors.
function variantsFor(major: EffectMajor) {
  if (major === 3) {
    return {
      imports:
        `import { Cause, Context, Data, Effect, Exit, Layer, Option, Runtime } from "effect"\n` +
        `import { Service } from "effect/Effect"`,
      tag: (self: string, type: string, id: string = self) =>
        `Context.Tag("${id}")<\n  ${self},\n  ${type}\n>()`,
      serviceConstructor: `Service<PrismaService>()`,
      serviceConfigKey: "effect",
      txContextVar: "runtime",
      txContextExpr: "Effect.runtime<R>()",
      txRun: "Runtime.runPromiseExit(runtime)",
      // effect v3's `Effect.Service` already provides a `.Default` layer.
      serviceStatics: "",
    };
  }
  return {
    imports: `import { Cause, Context, Data, Effect, Exit, Layer, Option } from "effect"`,
    tag: (self: string, type: string, id: string = self) =>
      `Context.Service<\n  ${self},\n  ${type}\n>()("${id}")`,
    serviceConstructor: `Context.Service<PrismaService>()`,
    serviceConfigKey: "make",
    txContextVar: "services",
    txContextExpr: "Effect.context<R>()",
    txRun: "Effect.runPromiseExitWith(services)",
    // effect v4's `Context.Service` has no auto `.Default`; expose `.layer`.
    serviceStatics: "\n  static readonly layer = Layer.effect(this, this.make)",
  };
}

async function generateUnifiedService(
  models: DMMF.Model[],
  mappings: DMMF.Mappings["modelOperations"],
  outputPath: string,
  clientImportPath: string,
  hasTypedSql: boolean,
  major: EffectMajor,
  noCheck: boolean,
) {
  const rawSqlOperations = generateRawSqlOperations(hasTypedSql);
  const modelOperations = generateModelOperations(models, mappings);
  const v = variantsFor(major);

  const runtimeImport = hasTypedSql
    ? `\nimport * as runtime from "@prisma/client/runtime/client"`
    : "";

  const serviceContent = `${headerFor(noCheck)}
${v.imports}
import { Prisma, PrismaClient } from "${clientImportPath}"${runtimeImport}

export class PrismaClientService extends ${v.tag("PrismaClientService", "PrismaClient")} {}

// A client created with client.$extends(...) (e.g. @prisma/extension-accelerate).
// Its static type is not structurally compatible with PrismaClient — extended
// delegates use different generic signatures — but at runtime every operation
// this service uses remains available, as do $connect/$disconnect and batch
// $transaction. The exception is $on, which Prisma strips from extended
// clients (call it on the base client before $extends). Requiring every model
// delegate property (via TypeMap) makes a client generated from a different
// schema, or an incomplete mock, a compile error, while still accepting any
// extension of this schema's client.
export type ExtendedPrismaClientLike = {
  $transaction(...args: ReadonlyArray<any>): Promise<any>
  $queryRaw(...args: ReadonlyArray<any>): Promise<any>
  $executeRaw(...args: ReadonlyArray<any>): Promise<any>
} & {
  [K in Prisma.TypeMap["meta"]["modelProps"]]: unknown
}

// Builds the PrismaClientService layer from a plain or extended client.
// The cast is sound at runtime (see ExtendedPrismaClientLike above), but an
// extension's type-level changes (e.g. result extensions adding computed
// fields, or extra query args like Accelerate's cacheStrategy) are not
// reflected in the service's types; at runtime all operations go through the
// extended client and behave per the extension.
export const layerFromPrismaClient = (
  client: PrismaClient | ExtendedPrismaClientLike,
) => Layer.succeed(PrismaClientService, client as PrismaClient)

export class PrismaTransactionClientService extends ${v.tag("PrismaTransactionClientService", "Prisma.TransactionClient")} {}

export class PrismaUniqueConstraintError extends Data.TaggedError("PrismaUniqueConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaForeignKeyConstraintError extends Data.TaggedError("PrismaForeignKeyConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRecordNotFoundError extends Data.TaggedError("PrismaRecordNotFoundError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRelationViolationError extends Data.TaggedError("PrismaRelationViolationError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRelatedRecordNotFoundError extends Data.TaggedError("PrismaRelatedRecordNotFoundError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaTransactionConflictError extends Data.TaggedError("PrismaTransactionConflictError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaValueTooLongError extends Data.TaggedError("PrismaValueTooLongError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaValueOutOfRangeError extends Data.TaggedError("PrismaValueOutOfRangeError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaDbConstraintError extends Data.TaggedError("PrismaDbConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaConnectionError extends Data.TaggedError("PrismaConnectionError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaMissingRequiredValueError extends Data.TaggedError("PrismaMissingRequiredValueError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaInputValidationError extends Data.TaggedError("PrismaInputValidationError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export type PrismaCreateError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaUpdateError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelationViolationError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

export type PrismaDeleteError =
  | PrismaForeignKeyConstraintError
  | PrismaRelationViolationError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

export type PrismaFindOrThrowError =
  | PrismaConnectionError
  | PrismaRecordNotFoundError

export type PrismaFindError =
  | PrismaConnectionError

export type PrismaDeleteManyError =
  | PrismaForeignKeyConstraintError
  | PrismaRelationViolationError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaUpdateManyError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelationViolationError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

// Generic mapper for raw operations and fallback
const mapError = (error: unknown, operation: string, model: string): PrismaError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  // Unknown errors are not handled and will be treated as defects
  throw error;
}

// Specific mappers to narrow error types per operation

// Create, Upsert
const mapCreateError = (error: unknown, operation: string, model: string): PrismaCreateError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// Update
const mapUpdateError = (error: unknown, operation: string, model: string): PrismaUpdateError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// Delete
const mapDeleteError = (error: unknown, operation: string, model: string): PrismaDeleteError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// FindOrThrow
const mapFindOrThrowError = (error: unknown, operation: string, model: string): PrismaFindOrThrowError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
    }
  }
  throw error;
}

// Find
const mapFindError = (error: unknown, operation: string, model: string): PrismaFindError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
    }
  }
  throw error;
}

// DeleteMany
const mapDeleteManyError = (error: unknown, operation: string, model: string): PrismaDeleteManyError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// UpdateMany
const mapUpdateManyError = (error: unknown, operation: string, model: string): PrismaUpdateManyError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// The union of every operation any model supports, derived from the client's
// own TypeMap so it flows through the configured client import rather than a
// hardcoded @prisma/client runtime specifier.
type Operation = {
  [Model in keyof Prisma.TypeMap["model"]]: keyof Prisma.TypeMap["model"][Model]["operations"]
}[keyof Prisma.TypeMap["model"]]

// The view of the client that operations call delegates through: model and
// method names stay checked, and each call's argument is checked against the
// operation's real input type — only the returns are untyped, because a
// delegate's own generics cannot bind the service's type parameter, so each
// operation's declared Result<> return carries the types instead. Non-operation
// members (a delegate's \`fields\`, direct function properties like $queryRaw)
// keep their real types, so calling a member outside Operation is a compile
// error rather than a silently unchecked call.
type LooseDelegates = {
  [K in keyof Prisma.TransactionClient]: Prisma.TransactionClient[K] extends (...args: never) => unknown
    ? Prisma.TransactionClient[K]
    : {
        [M in keyof Prisma.TransactionClient[K]]: M extends Operation
          ? (args: Prisma.Args<Prisma.TransactionClient[K], M>) => Promise<any>
          : Prisma.TransactionClient[K][M]
      }
}

const clientOrTx = (client: PrismaClient) => Effect.map(
  Effect.serviceOption(PrismaTransactionClientService),
  (tx) => Option.getOrElse(tx, () => client) as unknown as LooseDelegates,
);

// groupBy's input validation (having/orderBy fields must appear in "by")
// cannot be expressed via Prisma.Args, so it is restated here — once, shared
// across all models — instead of inline per model. Each helper is derivable
// from the call's args T (and the model's GroupByArgs for the orderBy
// requiredness), matching the validation Prisma's own delegate performs.
type GroupByHasSkipOrTake<T> = Prisma.Or<
  Prisma.Extends<"skip", Prisma.Keys<T>>,
  Prisma.Extends<"take", Prisma.Keys<T>>
>
type GroupByByFields<T extends { by?: unknown }> = Prisma.MaybeTupleToUnion<T["by"]>
type GroupByOrderFields<T extends { orderBy?: unknown }> =
  Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>> & string>
type GroupByOrderByArgument<GroupByArgs extends { orderBy?: unknown }, T> =
  Prisma.True extends GroupByHasSkipOrTake<T>
    ? { orderBy: GroupByArgs["orderBy"] }
    : { orderBy?: GroupByArgs["orderBy"] }
type GroupByOrderByErrors<T extends { by?: unknown; orderBy?: unknown }> = {
  [P in GroupByOrderFields<T>]: P extends GroupByByFields<T>
    ? never
    : \`Error: Field "\${P}" in "orderBy" needs to be provided in "by"\`
}[GroupByOrderFields<T>]
type GroupByInputErrors<T extends { by?: unknown; orderBy?: unknown; having?: unknown }> =
  (T["by"] extends never[] ? Prisma.True : Prisma.False) extends Prisma.True
  ? \`Error: "by" must not be empty.\`
  : Prisma.Has<GroupByByFields<T>, Prisma.GetHavingFields<T["having"]>> extends Prisma.False
  ? {
      [P in Prisma.GetHavingFields<T["having"]>]: P extends GroupByByFields<T>
        ? never
        : P extends string
        ? \`Error: Field "\${P}" used in "having" needs to be provided in "by".\`
        : [Error, "Field ", P, \` in "having" needs to be provided in "by"\`]
    }[Prisma.GetHavingFields<T["having"]>]
  : "take" extends Prisma.Keys<T>
  ? "orderBy" extends Prisma.Keys<T>
    ? Prisma.Has<GroupByByFields<T>, GroupByOrderFields<T>> extends Prisma.True
      ? {}
      : GroupByOrderByErrors<T>
    : 'Error: If you provide "take", you also need to provide "orderBy"'
  : "skip" extends Prisma.Keys<T>
  ? "orderBy" extends Prisma.Keys<T>
    ? Prisma.Has<GroupByByFields<T>, GroupByOrderFields<T>> extends Prisma.True
      ? {}
      : GroupByOrderByErrors<T>
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
  : Prisma.Has<GroupByByFields<T>, GroupByOrderFields<T>> extends Prisma.True
  ? {}
  : GroupByOrderByErrors<T>

export class PrismaService extends ${v.serviceConstructor}("PrismaService", {
  ${v.serviceConfigKey}: Effect.gen(function* () {
    const client = yield* PrismaClientService;
    return {
      $transaction: <A, E, R>(
        effect: Effect.Effect<A, E, R>,
        options?: {
          maxWait?: number
          timeout?: number
          isolationLevel?: Prisma.TransactionIsolationLevel
        }
      ) =>
        Effect.gen(function* () {
          const ${v.txContextVar} = yield* ${v.txContextExpr};
          const tx = yield* Effect.serviceOption(PrismaTransactionClientService);
          return yield* Option.match(tx, {
            onSome: (tx) => effect,
            onNone: () =>  Effect.tryPromise({
              try: () =>
                client.$transaction(async (tx) => {
                  const exit = await ${v.txRun}(
                    effect.pipe(Effect.provideService(PrismaTransactionClientService, tx)) as Effect.Effect<A, E, R>,
                  )
                  if (Exit.isSuccess(exit)) {
                    return exit.value
                  }
                  throw Cause.squash(exit.cause)
                }, options),
              catch: (error) => error as E,
            }) as unknown as Effect.Effect<A, E, R>,
          })
        }),
      ${rawSqlOperations}

      ${modelOperations}
    }
  })
}) {${v.serviceStatics}
}
`;

  await fs.writeFile(outputPath, serviceContent);
}
